sudo: false
language: node_js
node_js:
- '7'
git:
  depth: 3
cache:
  directories:
  - "$HOME/.npm"
  - node_modules
  - assets/aircraft
  - assets/airlines
  - assets/airports
  - assets/fonts
  - assets/images
notifications:
  slack:
    secure: RvZTkzZ1cClaDj0XZJEkmktGzPVnOtuZAVMqn+uE2ipoCXnOML3hEprJH3vJSUOHikzAhkBokAmfP3TMWyRkGv5xVF30+LoR2PZpyfaHrtZKnqdGaIXNxjb7CWQeQ3Pv8bx4vzm+ztTDs1oJZWW8qdknqO6Y3lHoq4/JadIVkSACFK9RmcTxg9QfzViAn6s2x2DUaTbTtD06nyAndG/om6aa6fVGMmrhoYVbpham6Gwn9OaU2tzk+SyOJGX2N3jUikfP5SnkQ7JkWkbsXOhEZbz8gXmIL1GUa1DuazS7fpc2BtHqaXtM2fLtTzl/Kk89SaXctNeYvgzgIk68vpxqFUYsYxerb5+sjLLe3bhaatZ3WRliKn6nA30LhVqzBJO9wzl/11LADjK3CltsnfuiWWh4k9M7+A1FYeXquHrPU8kn6AGucsc4+JXDcAYOcPT8GsJfev9k1dUqq+yB1YFx3v2c6OTLqJwjL/MVeSaf1PpONSWlU8MFRj18m6UDyKoqCJlwGTTWDiV5dpEu1RYQ4aWoBHfKtzxGNZ4WW3R/6PeW0E7CTQgSaEhcg/c5uujcdI4UW35MUfKVXrKf2SJPFWgV4XEkEtcdySXhnEI5PQOuOD6RIeDwOq2eBN3uIEKCglKdsMyB2EluDSnsOwkLG102Klb+zlPklcQr4W+YqHM=
